@baseUrl = http://localhost:3000

# RECADOS

### AppControllerGetHello
GET {{baseUrl}}/recados/
?limit=10
&offset=0

###
GET {{baseUrl}}/recados/12

###
POST {{baseUrl}}/recados/
Content-Type: application/json

 {
    "texto": "NOVO RECADO",
    "deId": 7,
    "paraId": 9
 }

###
PATCH {{baseUrl}}/recados/4/
Content-Type: application/json

 {
    "texto": "Teste mudança de texto do recado",
    "lido": true
 }

###
DELETE {{baseUrl}}/recados/2






#################################################################################################





# PESSOAS

### lista todas as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0

###
GET {{baseUrl}}/pessoas/2

###
POST {{baseUrl}}/pessoas/
Content-Type: application/json

 {
    "name": "Roberto Esteves",
    "email": "betoesteves@email.com",
    "password": "123456"
 }

###
PATCH {{baseUrl}}/pessoas/6/
Content-Type: application/json

 {
    "name": "Josival",
    "password": "654321"
 }

###
DELETE {{baseUrl}}/pessoas/5
