@baseUrl = http://localhost:3000

# RECADOS

### AppControllerGetHello
# @name AppRecadoController
GET {{baseUrl}}/recados/?limit=10&offset=0

###
GET {{baseUrl}}/recados/2

###
POST {{baseUrl}}/recados/
Content-Type: application/json

 {
    "texto": "Novo Recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2026-08-23T17:31:07.705Z"
 }

###
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

 {
    "texto": "Atualiza Recado 2",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2026-08-23T17:31:07.705Z"
 }

###
DELETE {{baseUrl}}/recados/2
