@baseUrl = http://localhost:3000

# RECADOS

### AppControllerGetHello
# @name AppRecadoController
GET {{baseUrl}}/recados/?limit=10&offset=0

###
GET {{baseUrl}}/recados/2

###
POST {{baseUrl}}/recados/
Content-Type: application/json

 {
    "texto": "4 NOVO RECADO 28/08",
    "de": "Joana",
    "para": "João da Silva"
 }

###
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

 {
    "texto": "Atualiza Recado 4 27/08 ATUALIZADO"
 }

###
DELETE {{baseUrl}}/recados/3
